### ISSUE TITLE
"Fehler 502 Bad Gateway" when Uploading 3 GB file

### ISSUE THREAD

**Issue by theonlytruth** [schorschii/OCO-Server#23]
Hey schorschii,

I tried to upload a exe file with size about 3 GB. When the upload is finished it shows me the following error message and no new package is created:

```
Fehler 502 Bad Gateway
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Bad Gateway</title>
</head><body>
<h1>Bad Gateway</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
</p>
<hr>
<address>Apache/2.4.54 (Debian) Server at oco.xxx.xxx Port 443</address>
</body></html>
```

![grafik](https://user-images.githubusercontent.com/5502973/194277033-5602e5da-9738-4681-9f43-b44cbe2b7c58.png)

Could this result from the large file size? Is this a problem on our setup or with OCO itself? I think at least the error message should have another look. ;)

Greetings from the other side. :)
Carsten

**Comment by schorschii** [comment]
Thanks for reporting this. It turns out to be an Apache configuration issue. After upgrading the server to Debian 11, additional configuration values are necessary to allow uploading of large files. I'll add this to the server installation documentation.
Please try to upload it again now, I'm awaiting your package on the other side :)
