### ISSUE TITLE
Line 309 not translated

### ISSUE THREAD

**Issue by lyonelf** [schorschii/OCO-Server#29]
I have translated this line but in   web portal it stay in english

	'self_registration' => 'Auto-enregistrement',

![2023-04-28_10h19_10](https://user-images.githubusercontent.com/34097487/235094430-6c016fde-c905-43d5-bb10-4ac55c162717.png)

**Comment by theonlytruth** [comment]
Did you first register this computer and did then add translation for this string? Or was translation first?

If I'm right "Self Registration" is only a text which is saved with the computer informations when you register it. If you then change the language (or add a translation the text stays the same as before.

**Comment by lyonelf** [comment]
No no, translation was made before injected the PC

**Comment by schorschii** [comment]
The text "Self Registration" is saved forever in the description field of the computer when registering it. The problem is that `api-agent.php` is called from the agent (not from your web browser) and since it does not send a language header, the English text will always be used, no matter what language is set in your browser.

I'm going to change the behavior as follows:
- save only the translation key "self_registration" in the description field without date (date is redundant because there is already a separate field for it)
- send the description through `LANG()` before displaying it in the browser, this will replace "self_registration" with the translated text
