### ISSUE TITLE
Deny login during deployment of large software packages

### ISSUE THREAD

**Issue by VRDD** [schorschii/OCO-Server#35]
While working with your splendid product we came across an idea: Would it be possible to deny a login of users while a sw deployment has startet?

**Comment by schorschii** [comment]
Thanks @VRDD :)
We already talked to each other directly for this, and while I think it would be an interesting feature, I can't find any method (in the Windows registry) to lock the login screen. So I don't think this is possible with Windows.

But I have another idea. The problem basically is, when updating or uninstalling software while a user has the program still open, the job fails because files of running programs can't be deleted or overwritten on Windows. A solution might be to force quit the program by prepending `taskkill /F /IM yourprogram.exe` to the (un)installation procedure.
