### ISSUE TITLE
LAPS in OCO

### ISSUE THREAD

**Issue by BornTKill** [schorschii/OCO-Server#42]
Good Morning,

I have bought 20 licenses recently and also was checking LAPS4Linux.
I have OSX, Ubuntu and Win in my environnement (100Users), and was wondering if LAPS could be integrated in OCO ? WIll be easier than having a domain to use LDAP once computers joined the domain.

Best regards.

**Comment by BornTKill** [comment]
I realized that this extension exists https://github.com/schorschii/OCO-Server-Extensions/tree/master/laps-launcher
but it leverage LAPS4LINUX. What do you think about having local admin password directly in OCO ?

**Comment by schorschii** [comment]
Thanks for supporting my work.

It's indeed an interesting idea to use OCO as database for LAPS. However, this requires quite a bit of work to integrate this. Since I'm using LAPS in Active Directory environments (with transfer to OpenLDAP in sight), I have no plans to realize that. However, if you need this for your environment, you may hire me to implement this. If you are interested you can [contact me](https://georg-sieber.de/?page=impressum) for a quote.
